name: Dragon Dungeon Full Prod Release

on:
  release:
    types: [published]

jobs:
  build_push:
    name: Build & Push Dragon Dungeon
    runs-on: ubuntu-latest
    steps:
      - name: âš™ Checkout Repo
        uses: actions/checkout@v2
      
      - name: ğŸ‘¤ Log In to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: ğŸ”– Generate Release Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: samuelbeep/dragondungeon
      
      - name: ğŸ±â€ğŸ’» Build & Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
